=== nikolai/stomo/src/bpel-stomodel-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://sm.com/bpel/stomodel-config"
            xmlns="http://www.w3.org/2001/XMLSchema"
            xmlns:tns="http://sm.com/bpel/stomodel-config"
            elementFormDefault="qualified"
            blockDefault="#all">

    <element name="BpelStoModelConfiguration" type="tns:StoModelConfig">
    </element>
    <complexType name="StoModelConfig">
        <sequence>
            <element name="ActivityConfig" type="tns:TAtomicActivityConfig" minOccurs="0" maxOccurs="unbounded"/>
            <element name="IfActivityConfig" type="tns:TIfBranchConfig" minOccurs="0" maxOccurs="unbounded"/>
            <element name="FlowActivityConfig" type="tns:TFlowActivityConfig" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="TActivityConfig">
        <sequence>
            <element name="activityName" type="string"/>
        </sequence>
    </complexType>
    <complexType name="TAtomicActivityConfig">
        <complexContent>
            <extension base="tns:TActivityConfig">
                <sequence>
                    <element name="TimeDistribution" type="tns:TTimeDistribution" maxOccurs="unbounded"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="TTimeDistribution">
        <sequence>
            <element name="time" type="int"/>
            <element name="probability" type="tns:Probability"/>
        </sequence>
    </complexType>
    <complexType name="TIfBranchConfig">
        <complexContent>
            <extension base="tns:TActivityConfig">
                <sequence>
                    <element name="probabilityOfBranch" type="tns:Probability" maxOccurs="unbounded"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <simpleType name="Probability">
        <restriction base="double"/>
    </simpleType>
    <complexType name="TFlowActivityConfig">
        <complexContent>
            <extension base="tns:TActivityConfig">
                <sequence>
                    <element name="countOfWaitedResults" minOccurs="0" type="unsignedInt"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
</schema>

=== nikolai/stomo/stoMC-simpleBP.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<BpelStoModelConfiguration xmlns="http://sm.com/bpel/stomodel-config"
                           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                           xsi:schemaLocation="http://sm.com/bpel/stomodel-config src/bpel-stomodel-config.xsd">
    <ActivityConfig>
        <activityName>Receive1</activityName>
        <TimeDistribution>
            <time>1</time>
            <probability>0.98</probability>
        </TimeDistribution>
        <TimeDistribution>
            <time>2</time>
            <probability>0.01</probability>
        </TimeDistribution>
        <TimeDistribution>
            <time>3</time>
            <probability>0.01</probability>
        </TimeDistribution>
    </ActivityConfig>
    <ActivityConfig>
        <activityName>Assign1</activityName>
        <TimeDistribution>
            <time>3</time>
            <probability>0.98</probability>
        </TimeDistribution>
        <TimeDistribution>
            <time>1</time>
            <probability>0.01</probability>
        </TimeDistribution>
        <TimeDistribution>
            <time>2</time>
            <probability>0.01</probability>
        </TimeDistribution>
    </ActivityConfig>
    
</BpelStoModelConfiguration>

=== nikolai/stomo/stoMC-2ofNbpel.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<BpelStoModelConfiguration xmlns="http://sm.com/bpel/stomodel-config"
                           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                           xsi:schemaLocation="http://sm.com/bpel/stomodel-config src/bpel-stomodel-config.xsd">
    <ActivityConfig>
        <activityName>Invoke0</activityName>
        <TimeDistribution>
            <time>1</time>
            <probability>0.98</probability>
        </TimeDistribution>
        <TimeDistribution>
            <time>2</time>
            <probability>0.01</probability>
        </TimeDistribution>
        <TimeDistribution>
            <time>3</time>
            <probability>0.01</probability>
        </TimeDistribution>
    </ActivityConfig>
    <ActivityConfig>
        <activityName>Invoke1</activityName>
        <TimeDistribution>
            <time>1</time>
            <probability>0.98</probability>
        </TimeDistribution>
        <TimeDistribution>
            <time>2</time>
            <probability>0.01</probability>
        </TimeDistribution>
        <TimeDistribution>
            <time>3</time>
            <probability>0.01</probability>
        </TimeDistribution>
    </ActivityConfig>
    <ActivityConfig>
        <activityName>Invoke2</activityName>
        <TimeDistribution>
            <time>1</time>
            <probability>0.98</probability>
        </TimeDistribution>
        <TimeDistribution>
            <time>2</time>
            <probability>0.01</probability>
        </TimeDistribution>
        <TimeDistribution>
            <time>3</time>
            <probability>0.01</probability>
        </TimeDistribution>
    </ActivityConfig>
    <ActivityConfig>
        <activityName>InvokeM</activityName>
        <TimeDistribution>
            <time>1</time>
            <probability>0.98</probability>
        </TimeDistribution>
        <TimeDistribution>
            <time>2</time>
            <probability>0.01</probability>
        </TimeDistribution>
        <TimeDistribution>
            <time>3</time>
            <probability>0.01</probability>
        </TimeDistribution>
    </ActivityConfig>
    <ActivityConfig>
        <activityName>InvokeN</activityName>
        <TimeDistribution>
            <time>1</time>
            <probability>0.98</probability>
        </TimeDistribution>
        <TimeDistribution>
            <time>2</time>
            <probability>0.01</probability>
        </TimeDistribution>
        <TimeDistribution>
            <time>3</time>
            <probability>0.01</probability>
        </TimeDistribution>
    </ActivityConfig>
    <ActivityConfig>
        <activityName>InvNp1</activityName>
        <TimeDistribution>
            <time>1</time>
            <probability>0.98</probability>
        </TimeDistribution>
        <TimeDistribution>
            <time>2</time>
            <probability>0.01</probability>
        </TimeDistribution>
        <TimeDistribution>
            <time>3</time>
            <probability>0.01</probability>
        </TimeDistribution>
    </ActivityConfig>
    <IfActivityConfig>
        <activityName>If1</activityName>
        <probabilityOfBranch>0.25</probabilityOfBranch>
    </IfActivityConfig>
    <IfActivityConfig>
        <activityName>If2</activityName>
        <probabilityOfBranch>0.33</probabilityOfBranch>
    </IfActivityConfig>
    <IfActivityConfig>
        <activityName>IfM</activityName>
        <probabilityOfBranch>0.5</probabilityOfBranch>
    </IfActivityConfig>
    <FlowActivityConfig>
        <activityName>Flow1</activityName>
        <countOfWaitedResults>2</countOfWaitedResults>
    </FlowActivityConfig>
</BpelStoModelConfiguration>
